{% set name = "jupyter-rsession-proxy" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a830def4c6922f6bd0f63d015bd8e56e2087e15954dfdb6c0cbd5397d01e8b2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python >=3
  run:
    - jupyter-server-proxy >=3.1
    - python >=3
    - setuptools

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jupyter_rsession_proxy

about:
  home: https://github.com/jupyterhub/jupyter-rsession-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter extension to proxy RStudio's rsession

extra:
  recipe-maintainers:
    - xhochy
