{% set name = "jupyter-rsession-proxy" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47fedffa51e613bb2ba1d10e1b0b90469db35315d3e9af3d41a4e7d4eb4e97c3

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - jupyter-server-proxy
    - python >=3
    - setuptools

test:
  imports:
    - jupyter_rsession_proxy

about:
  home: https://github.com/jupyterhub/jupyter-rsession-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter extension to proxy RStudio's rsession

extra:
  recipe-maintainers:
    - xhochy
