{% set name = "jupyter-rsession-proxy" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 826bc3678bcd7e815ff3592874c9599882c5a83da42381ddb9297a81601ac6c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jupyter-server-proxy >=3.1
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - jupyter_rsession_proxy

about:
  home: https://github.com/jupyterhub/jupyter-rsession-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter extension to proxy RStudio's rsession

extra:
  recipe-maintainers:
    - xhochy
