travis:
  secure:
    BINSTAR_TOKEN: KgpM5qbvF94tayVt8xp5/5n/uIJSX3Kz0OvvXTHmaam/hn+s+PIw284DBYq3JGv4vvr6tBKZF77VLw70Fd7K8LjQ1xmWTpQOeRdwU3TBTjYC9zHXjr1blq+13Bx0FC3+lqSVjia7JLmsv69CBFpUE0No/fGrN09YjmVnweXgGOj8NU7el6n/F6FyORTTS1/ZQL5dPuuVl8KGcSqBKFfxGbahLWNNsItPcxm/pTpInwV6Ke8FiiNYj2vbpa4KXGUCbTCQtu3c5WGM7BnRjAlX+u5DOG9oqv3rKnTKzlfZ67MCwERCaWDCJAAFoZlOLH2VD22b9hgtFcwcozeRTltO016xCtOmkNnZxih90Zb0aQlI2G7vfHJ40HKqZu+KsD2EAAD9Gvz1sMqi7ljxG1pV1jaOEEmNKsRYVYc6mfblaQXR4bpmA0QH/Asv/HJNSnn+pb0z4uJXaaxyIWE4PDzdKDw3YmQVhvHD/CPD/nj9iMnFou9uG3E1jygtBNmZH6Ifb/H2XUYND7YJLKvefmim11BhZGGZO/lijOM0vmjf23gEH3It7cQ41827d6DjOXZs/JWuTs6IWUitgCIYWqz6i9fr/uLMBTVmeMUaoe0o2wzFiiFkmvxbDTWBq/jhi6H3lYVi+/3BQ2A8bL0cjUx8kuRbuk8rxN+45l3DNjAp1H8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
